travis:
  secure:
    BINSTAR_TOKEN: D+kkymwqTbJT15ou2OtEJtlG2dJ1W36CdGB6VhcGziE6M1ik5Cj9brhZWH9bu4HMgZl4YFZEXPbe7Ow9IeedcC9meD//AccyBKJNpoe7KtFmiXpl8mfyyJ6q2TSRSzhRt9wFMlf4qg9PVPD9+iWmvFRopwqGnZfkYipCbTCLEkQmxuKp7+CCXnGa+YKSzxLRxmCu3QN2RUHvWfTZRGamOw6q9pqAmR1RnZRh5dWsH7mOzXwYYODnuV40hBtzvm7rpelN+qsDi1xdFVsclKZMPAgcBL1A2/QIphMCgDsaF5ubuXjSaMQA0xCl78P1wnTyh7lrTz+0qtGxVrQ3+wEHOtSvm/i1pesc68Lm4/smqUR3cmI1opalsV/DrusfXtZIL6NzEUA2ZBAHhPL1lJoUBuq2ZhP4IDquZBe+l5GkZYlNTxb9qGc9QO3oxJEytvCnec6FTmDBbgIoqsI6E/W7cQaJiJH7gSNcgVD/yu23i5OFhN55oEnYylnhLB1nircb7rzNz8ToKGzC0hTCs9PnoLNaTQUzfazn01KsixGTKwVcVwYMX2pRkrYyexrjiO2QJYE5OTv1xu/fM1M8DsC8k5Cf0Cmaxx/X4VuO7+tdCqG8RfwBaxVHdhzdTm4T5pYhDPkVEvvab6lhNYR2NDZK8BhdsysW7n86nR7S9n6ChuA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
